get-to-update:
   image: docker.totvs.io/totvsmpn/get-to-update
   container_name: get-to-update
   restart: always
   environment:
     - MONGO_CONN=mongodb://mongo/aletaspmed
     - MONGO_USER=admin
     - MONGO_PWD=admin
   external_links:
     - mongo
    

